## Import libraries

In [ ]:
!pip install pyvi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 8.5 MB 15.3 MB/s 
     |████████████████████████████████| 965 kB 60.1 MB/s 


In [ ]:
!pip install underthesea

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 7.6 MB 5.4 MB/s 
     |████████████████████████████████| 235 kB 82.9 MB/s 
     |████████████████████████████████| 581 kB 45.8 MB/s 


In [ ]:
!pip install demoji

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 42 kB 1.5 MB/s 


In [ ]:
!pip install emoji

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 175 kB 13.7 MB/s 
  Created wheel for emoji: filename=emoji-1.7.0-py3-none-any.whl size=171046 sha256=8e7cb7aa622933e442721af9c308e06046ae0fed781a0d8618b20313b85f37da
  Stored in directory: /root/.cache/pip/wheels/8a/4e/b6/57b01db010d17ef6ea9b40300af725ef3e210cb1acfb7ac8b6
Successfully built emoji


In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive


In [ ]:
%cd '/content/gdrive/My Drive/LDS0_K276_BuiThiHuong/Topic2'

/content/gdrive/My Drive/LDS0_K276_BuiThiHuong/Topic2


In [ ]:
import time
import pandas as pd
import numpy as np
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.model_selection import train_test_split  
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
import matplotlib.pyplot as plt
# thu vien Tokenizer Viet
from pyvi import ViTokenizer, ViPosTagger
from wordcloud import WordCloud

import glob as gl
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import emoji
import re

# saving model libraries
from sklearn.pipeline import Pipeline
import pickle

# import import_ipynb
# from lib_NLP import *

In [ ]:
pip install ipynb

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
%cd '/content/gdrive/My Drive/LDS0_K276_BuiThiHuong/Topic2/lib'
%run function_lib.ipynb     #this is were my function was stored

/content/gdrive/My Drive/LDS0_K276_BuiThiHuong/Topic2/lib


In [ ]:
%cd '/content/gdrive/My Drive/LDS0_K276_BuiThiHuong/Topic2/'

/content/gdrive/My Drive/LDS0_K276_BuiThiHuong/Topic2


# Step 4&5: MODELING & EVALUATION/ ANALYZE AND REPORT

### Load data

Load undersampling data

In [ ]:
# list_files = gl.glob("outputs/X_train_us_self_?.csv")
# list_files

['outputs/X_train_us_1.csv', 'outputs/X_train_us_2.csv']

In [ ]:
# lst_data = []
# for file in list_files:
#     df_temp = pd.read_csv(file)
#     lst_data.append(df_temp)

In [ ]:
X_train_us = pd.read_csv('outputs/X_train_us_self.csv')

In [ ]:
y_train_us = pd.read_csv('outputs/y_train_us_self.csv')

In [ ]:
X_test = pd.read_csv('outputs/X_test_self.csv')

In [ ]:
y_test = pd.read_csv('outputs/y_test_self.csv')

In [ ]:
X_train_us = X_train_us.iloc[:,1:]

In [ ]:
y_train_us = y_train_us.iloc[:,1:]

In [ ]:
X_test = X_test.iloc[:,1:]

In [ ]:
y_test = y_test.iloc[:,1:]

Load oversampling data

In [ ]:
# list_files = gl.glob("outputs/X_train_os_?.csv")
# list_files

['outputs/X_train_os_1.csv',
 'outputs/X_train_os_2.csv',
 'outputs/X_train_os_3.csv',
 'outputs/X_train_os_4.csv']

In [ ]:
# lst_data = []
# for file in list_files:
#     df_temp = pd.read_csv(file)
#     lst_data.append(df_temp)

In [ ]:
# X_train_os = pd.concat(lst_data)

In [ ]:
X_train_os = pd.read_csv('outputs/X_train_os_self.csv')

In [ ]:
y_train_os = pd.read_csv('outputs/y_train_os_self.csv')

In [ ]:
X_train_os = X_train_os.iloc[:,1:]

In [ ]:
y_train_os = y_train_os.iloc[:,1:]

## MultinomialNB

### Build model

In [ ]:
clf_mb_us = MultinomialNB()
clf_mb_os = MultinomialNB()

In [ ]:
clf_mb_us.fit(X_train_us, y_train_us)
clf_mb_os.fit(X_train_os, y_train_os)

MultinomialNB()

In [ ]:
# save model
pickle.dump(clf_mb_us, open('outputs/MultinomialNB_us_self_model.sav', 'wb'))
pickle.dump(clf_mb_os, open('outputs/MultinomialNB_os_self_model.sav', 'wb'))

### Model Evaluation

In [ ]:
y_testhat_us = clf_mb_us.predict(X_test)
y_testhat_os = clf_mb_os.predict(X_test)

In [ ]:
# Evaluation - Undersampling
print(confusion_matrix(y_test, y_testhat_us))

[[8418  986]
 [ 524 1908]]


In [ ]:
print(classification_report(y_test, y_testhat_us))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92      9404
           1       0.66      0.78      0.72      2432

    accuracy                           0.87     11836
   macro avg       0.80      0.84      0.82     11836
weighted avg       0.88      0.87      0.88     11836



In [ ]:
# Evaluation - Oversampling
print(confusion_matrix(y_test, y_testhat_os))

[[8448  956]
 [ 597 1835]]


In [ ]:
print(classification_report(y_test, y_testhat_os))

              precision    recall  f1-score   support

           0       0.93      0.90      0.92      9404
           1       0.66      0.75      0.70      2432

    accuracy                           0.87     11836
   macro avg       0.80      0.83      0.81     11836
weighted avg       0.88      0.87      0.87     11836



### Prediction

In [ ]:
# # load model
# clf_mb_us = pickle.load(open('outputs/MultinomialNB_us_model.sav', 'rb'))

In [ ]:
df_clean_cv = pd.read_csv('outputs/df_clean_self_cv.csv')

In [ ]:
df_clean_cv = df_clean_cv.set_index('index')

In [ ]:
X = df_clean_cv.iloc[:,7:]

In [ ]:
y_hat = clf_mb_us.predict(X)

In [ ]:
y_hat[:5]

array([0, 0, 0, 0, 0])

In [ ]:
df_clean_predict = df_clean_cv.iloc[:,2:7].reset_index()
df_clean_predict['predict'] = y_hat
df_clean_predict.head()

index                                      restaurant  \
0      0                         Good Morning Restaurant   
1      1                              Hạt Dẻ Trùng Khánh   
2      2  Bột - Healthy & Weight Loss Food - Shop Online   
3      3                    Bánh Giò Chợ Nguyễn Công Trứ   
4      4                          Quán Quảng - Bún Quảng   

                                         review_text  review_score  \
0  Pizza phong cách Ý. Ngán hải sản nên cả nhà gh...           8.2   
1  - Vị trí: chỉ là 1 chiếc xe nho nhỏ nằm ở khu ...           8.0   
2  Nay lang thang trên BM thấy đang khuyến mãi xo...           8.2   
3  Quán nằm trong chợ Nguyễn Công Trứ, cũng dễ tì...           8.2   
4  Ngãi heo với heo thiệttttt 🐷🐷🐷\n🤤🤤 bún nem chả...           9.0   

                                   review_text_clean  review_score_new  \
0              phong_cách ngán rẻ trình_bày đẹp đúng                 0   
1  nho_nhỏ thôi đông chất_lượng thích sạch_sẽ cảm...                 0   
2             review khen cảm_nhận ngon ăn_no khô ok                 0   
3  dễ cần đông siêu ngon đặc_biệt ngọt đặc_biệt h...                 0   
4  ngon ngon bao ngon bao thơm bao no ngon ngon k...                 0   

   predict  
0        0  
1        0  
2        0  
3        0  
4        0

In [ ]:
pd.crosstab(df_clean_predict['review_score_new'],df_clean_predict['predict'])

predict               0     1
review_score_new             
0                 28099  3196
1                  1656  6501

In [ ]:
# save
df_clean_predict.to_excel('outputs/df_BernoulliNB_us_self_predict.xls', sheet_name='Sheet1', encoding='utf-8')

In [ ]:
1-1656/(1656+6501)

0.7969841853622656

## BernoulliNB

### Build model

In [ ]:
clf_bb_us = BernoulliNB()
clf_bb_os = BernoulliNB()

In [ ]:
clf_bb_us.fit(X_train_us, y_train_us)
clf_bb_os.fit(X_train_os, y_train_os)

BernoulliNB()

In [ ]:
# save model
pickle.dump(clf_bb_us, open('outputs/BernoulliNB_us_self_model.sav', 'wb'))
pickle.dump(clf_bb_os, open('outputs/BernoulliNB_os_self_model.sav', 'wb'))

### Model Evaluation

In [ ]:
y_testhat_us = clf_bb_us.predict(X_test)
y_testhat_os = clf_bb_os.predict(X_test)

In [ ]:
# Evaluation - Undersampling
print(confusion_matrix(y_test, y_testhat_us))

[[7806 1598]
 [ 435 1997]]


In [ ]:
print(classification_report(y_test, y_testhat_us))

              precision    recall  f1-score   support

           0       0.95      0.83      0.88      9404
           1       0.56      0.82      0.66      2432

    accuracy                           0.83     11836
   macro avg       0.75      0.83      0.77     11836
weighted avg       0.87      0.83      0.84     11836



In [ ]:
# Evaluation - Oversampling
print(confusion_matrix(y_test, y_testhat_os))

[[7545 1859]
 [ 781 1651]]


In [ ]:
print(classification_report(y_test, y_testhat_os))

              precision    recall  f1-score   support

           0       0.91      0.80      0.85      9404
           1       0.47      0.68      0.56      2432

    accuracy                           0.78     11836
   macro avg       0.69      0.74      0.70     11836
weighted avg       0.82      0.78      0.79     11836



## Conclusion
If focus on recall score of class 1 (dislike), the MultinomialMB is the best model, with recall score of class 1 = 78%, recall score of class 0 = 90% and Macro F1-score = 82% (precision of class 1 = 66%, precision of class 0 = 94%)

# Step 6: DEPLOYMENT & FEEDBACK/ACT

* Create a pipeline that helps end-user can use models easily.

## Build Pipeline

### Create def

In [ ]:
def data_cleaning(data):
    df = data.copy()

    # remove unnamed columns
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

    # feature "review_text"
    df_clean = df
    document = df_clean['review_text']

    # load edited emojicon
    file = open('lib/files/emojicon.txt', 'r', encoding="utf8")
    emoji_lst = file.read().split('\n')
    file.close()

    emoji_dict = {}
    lst_key = []
    lst_value = []
    for line in emoji_lst:
      key, value = line.split('\t')
      lst_key.append(key)
      lst_value.append(value)
      emoji_dict[key] = str(value)

    # load chosen words
    file = open('lib/files/chosen_words_full.txt', 'r', encoding="utf8")
    lst_chosen_words = file.read().split('\n')
    file.close()

    lst_spec_symbol = ['~','`','!','@','#','$','%','^','&','*','(',')','-','=','+',   '[','{','}','}','\\','|',';',':','"',     ',','<','.','>','/','?']
    lst_find_words = ['không ','ko ','kg ','chẳng ','chả ']
    lst_replace_words = ['không_','ko_','kg_','chẳng_','chả_']

    lst_document = []
    for doc in document:
      doc = doc.lower()

    # TEXT CLEANING
    # replace emojicons
      for i in range(len(lst_key)):
        doc = doc.replace(lst_key[i], ' '+lst_value[i])
      for j in doc:
        if j in emoji.UNICODE_EMOJI['en']: 
          doc = doc.replace(j, '')

    # word tokenize: sạch sẽ => sạch_sẽ
      doc = word_tokenize(doc, format='text')

    # remove special symbols
      rx = '[' + re.escape(''.join(lst_spec_symbol)) + ']' 
      doc = re.sub(rx, '', doc)

      doc = doc.replace('  ',' ')
      doc = doc.replace(' _',' ')
      doc = doc.replace('_ ',' ')

    # replace 'không ' to 'không_' co link words, v.v...
      for i in range(len(lst_find_words)):
        doc = doc.replace(lst_find_words[i], lst_replace_words[i]) 

    # remove stop_words
      lst_words = []
      for j in doc.split(' '):
        if j in lst_chosen_words: lst_words.append(j)
      doc = ' '.join(lst_words)  

      lst_document.append(doc)

    df_clean['review_text_clean'] = lst_document
    df_clean = df_clean.dropna()

    # create "review_score_new"
    df_clean['review_score_new'] = 1
    df_clean.loc[df_clean['review_score'] >= 6.8, 'review_score_new'] = 0
    df_clean['review_score_new'] = df_clean['review_score_new'].astype('int32')

    return df_clean

### Create fit_transform function

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
class Pre_Processing(BaseEstimator, TransformerMixin):
    def __init__(self):
        print('Khởi tạo đối tượng Pre-Processing')
    def fit(self, X, y=None):
        return self
    def transform(self, data, y=None):
        import pickle

        # load encoder model
        cv = pickle.load(open('outputs/CountVectorizer_self_model.sav','rb'))

        # data cleaning
        df = data.copy()
        df_clean = data_cleaning(df)

        # apply CountVectorizer
        cv_transformed = cv.transform(df_clean['review_text_clean'].dropna())
        cv_transformed = cv_transformed.toarray()
        df_clean_cv = pd.DataFrame(cv_transformed, columns=cv.get_feature_names())
        df_clean_cv = pd.concat([df_clean.reset_index(), df_clean_cv], axis=1)
      
        return df_clean_cv

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
class Create_XY(BaseEstimator, TransformerMixin):
    def __init__(self):
        print('Khởi tạo đối tượng Create_XY')
    def fit(self, X, y=None):
        return self
    def transform(self, data, y=None):
        import pickle
        
        df_clean_cv = data

        # create X, y   
        X = df_clean_cv.iloc[:,6:]
        y = df_clean_cv['review_score_new']

        return X, y

In [ ]:
# model_pre_processing = Pipeline(steps=[
#     ('Pre_Processing', Pre_Processing()),
#     ])

model_pre_processing = Pipeline(steps=[
    ('Pre_Processing', Pre_Processing()),
    ('Create_XY', Create_XY()),
    ])

model_mb = model_mb

Khởi tạo đối tượng Pre-Processing
Khởi tạo đối tượng Create_XY


## Save model

In [ ]:
# model_mb = pickle.load(open('outputs/MultinomialNB_us_self_model.sav', 'rb'))

In [ ]:
# save model
pickle.dump(model_pre_processing, open('outputs/Project2_model_pre_processing.sav', 'wb'))
pickle.dump(model_mb, open('outputs/Project2_mb_model_prediction.sav', 'wb'))

## Test model

In [ ]:
data = pd.read_csv('data_Foody.csv')
model_pre = pickle.load(open('outputs/Project2_model_pre_processing.sav', 'rb'))
model_predict = pickle.load(open('outputs/Project2_mb_model_prediction.sav', 'rb'))

In [ ]:
X_new, y_new = model_pre.transform(data)

In [ ]:
yhat = model_predict.predict(X_new)

In [ ]:
print(confusion_matrix(y_new, yhat))

[[28301  3196]
 [ 1927  6501]]


In [ ]:
print(classification_report(y_new, yhat))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92     31497
           1       0.67      0.77      0.72      8428

    accuracy                           0.87     39925
   macro avg       0.80      0.83      0.82     39925
weighted avg       0.88      0.87      0.87     39925



Conclusion:
* When having pipeline, end-user just do 1 little steps to make prediction.